// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Week04/internal/biz"
	"Week04/internal/data"
)

// Injectors from wire.go:

func InitTagUsecase() *biz.TagUsecase {
	tagRepo := data.NewTagRepo()
	tagUsecase := biz.NewTagUsecase(tagRepo)
	return tagUsecase
}
